### ISSUE TITLE
Can't perform extendMoment on browser. 

### ISSUE THREAD

**Issue by thurairaj92** [rotaready/moment-range#142]
I'm not sure if I'm reading the documentations wrongly but when I'm tried to DateRange.extendMoment(moment), I'm getting _Uncaught ReferenceError: DateRange is not defined_  and I checked moment is defined.

I'm using moment 2.17.1 and moment-range 3.0.0

**Comment by gf3** [comment]
@thurairaj92 can you paste your failing html/js please?

**Comment by gf3** [comment]
ping @thurairaj92

**Comment by AngularPlayer** [comment]
I have exactly the same problem.
I did a jsFiddle here : https://jsfiddle.net/a8tvqb9t/

**Comment by gf3** [comment]
hey all, thanks for the bug report. looks like there's an issue with how webpack is naming this module for browsers. the fix for now is to use it like so:

``` js
window['moment-range'].extendMoment(moment);
```

i'll try to address this as soon as i can and i'll update the docs immediately.

**Comment by AngularPlayer** [comment]
Thanks you :)

**Comment by gf3** [comment]
this is now the canonical way to use moment range and the docs have since been updated—thanks for the help everyone
