### ISSUE TITLE
iteration by [unit] does not work anymore

### ISSUE THREAD

**Issue by costezki** [rotaready/moment-range#148]
.by iteration seems to be broken. If I run the provided example (see below) I get the exception (see below).

**Exception:**
Error: Cannot read property 'call' of undefined
    at DateRange._byString (packages/benmgreene_moment-range.js:253:14)
    at DateRange.by (packages/benmgreene_moment-range.js:229:15)
    at Test.<anonymous> (server/generator.test.js:286:37)
    at run (packages/practicalmeteor:mocha-core/server.js:34:29)

**Example:**
284| const range = moment.range('2010-01-01', '2015-01-01');
285|
286|for (let month of range.by('month')) {
287|  month.format('YYYY-MM-DD');
288|}

**Comment by gf3** [comment]
hi @costezki it should definitely work for you. two things that could be an issue: 1) are you using the latest version, and 2) have you properly extended moment? e.g.:

<img width="627" alt="screen shot 2017-02-13 at 9 48 57 am" src="https://cloud.githubusercontent.com/assets/18397/22887913/dcb46ddc-f1d1-11e6-812e-cb187abdac74.png">

**Comment by dannymy** [comment]
I've also encountered some problems with iteration, `3.0.0` installed. Imports and extends:
```
import * as Moment                      from 'moment';
const extendFn                          = require('moment-range').extendMoment;
const moment                            = extendFn(Moment);
```
Where `rangeStart` and `rangeEnd` are Moment objects and `dayTimeRange` is a valid range.
```
let dayTimeRange = moment.range(rangeStart, rangeEnd);
dayTimeRange.by('hours', hour => { });
```
and `dayTimeRange.by('hours')` 

Both these examples produce nothing and don't work anymore in the app.
But as I see from the source, `by` does not accept a function as a second parameter any more.

**Comment by bleuscyther** [comment]
(2.2)only works if i use es6-promise
: import Promise from 'es6-promise';

**Comment by gf3** [comment]
@dannymy the iteration methods have changed in `3.0`, check out the docs:

- [#by](https://github.com/gf3/moment-range#by)
- [#byRange](https://github.com/gf3/moment-range#byRange)
- [#reverseBy](https://github.com/gf3/moment-range#reverseBy)
- [#reverseByRange](https://github.com/gf3/moment-range#reverseByRange)

**Comment by gf3** [comment]
@bleuscyther `2` doesn't have any dependencies on or make use of any promises
