### ISSUE TITLE
Webpack + UglifyJs error

### ISSUE THREAD

**Issue by Eldair** [rotaready/moment-range#153]
Hello,

When using laravel-mix with `npm run production` there is an error in compiling for this package
```
 ERROR  Failed to compile with 1 errors

 error

/js/main.a99681d2bb01e8789a80.js from UglifyJs
SyntaxError: Unexpected token: name (DateRange) [./~/moment-range/lib/moment-range.js:24,0][/js/main.a99681d2bb01e8789a80.js:29290,6]
```

This just started happening after 3.0.2

**Comment by Eldair** [comment]
Fixed by using
```
import {extendMoment} from 'moment-range/dist/moment-range.js';
```
instead of previous
```
import {extendMoment} from 'moment-range';
```

**Comment by WebSeed** [comment]
Yeah broken for us too since https://github.com/gf3/moment-range/commit/196adb308e5c075fa8e4b46b09773efd12298d38

I.e. think webpack 2 is now pulling in the `lib` files instead of `dist` (`"module": "lib/moment-range.js"`)

**Comment by wells** [comment]
I can also confirm this error and that the temporary fix works. I'm going to stay back on 2.2.0 until this is fixed.

**Comment by victoriafrench** [comment]
looking at this. shouldn't be hard to fix.

**Comment by gf3** [comment]
wow rude webpack—i don't have a lot of spare time to look into this; @victoriafrench let me know if you have any ideas!

**Comment by victoriafrench** [comment]
adding some notes for historical reference:

webpack 2 [argument on supporting `module`](https://github.com/webpack/webpack/issues/1979) and hopefully continuing to ignore `jsnext:main`

webpack 1 uses the [following in order](https://github.com/webpack/docs/wiki/Configuration#resolvepackagemains):
`["webpack", "browser", "web", "browserify", ["jam", "main"], "main"]`

webpack 2 uses the [following in order](https://github.com/webpack/webpack/blob/40aac864fd88495cd56dbec9bab522f8f34a47ea/lib/WebpackOptionsDefaulter.js#L82)
* if `options.target` is set to `web` or `webworker`
    `["browser", "module", "main"]`
* else
    `["module", "main"]`

browserify prefers [the order](https://github.com/substack/browserify-handbook) `["browserify", "browser", "module", "main"]`

> I do not know if browserify can digest webpack modules. Node and Rollup have issues with webpacked modules.

current thinking the following changes:

`"browser"` to point to dist which supports webpack 1 and 2, as well as browserify
`"jsnext:main"` to point to lib for rollup
`"module"` should be removed until a pure es6 (non harmony) module is transpiled and shipped
`"browserify"` should be added later if anyone with browserify digestion problems need it
`"main"` should point to lib for node. although once module is reintroduced nothing will ever read main.

**this was just a brain dump here for historical purposes**

**Comment by victoriafrench** [comment]
@Eldair Does laravel-mix set the webpack target to `web`? I can't seem to find any reference to it in their source code.

**Comment by victoriafrench** [comment]
Sent in a PR to unscrew you all until we can get the ordering resolved.

**Comment by gf3** [comment]
fixed in [`3.0.3`](https://github.com/gf3/moment-range/releases/tag/v3.0.3)

**Comment by gf3** [comment]
thanks @victoriafrench

**Comment by Eldair** [comment]
@victoriafrench nop, I don't find it either so I suppose it is 'web' as default (if the info is still needed)
