### ISSUE TITLE
bower package is missing dist

### ISSUE THREAD

**Issue by thany** [rotaready/moment-range#155]
Install moment-range 3.0.x using bower, and the `dist` directory will be missing. Can it please be added? Used to be fine for 2.2.0 but since 3.0.x it's missing.

**Comment by victoriafrench** [comment]
@gf3 this issue will go away with the PR as well. I would have included the files but there is no bower config in the project. Not sure how the bower release is being done.

**Comment by gf3** [comment]
@thany @victoriafrench bower was purposefully removed in 3.0

**Comment by victoriafrench** [comment]
@gf3 did you unregister with bower? If not then bower is still shipping releases based on release tags and off the original bower config

`bower unregister moment-range`

**Comment by gf3** [comment]
@victoriafrench not yet, technically it's deprecated as of `3.0` and i will remove it from the register for `4.0`

**Comment by thany** [comment]
Bummer, I'm using bower for all clientside-loading packages in some of my projects. One thing that I need, is for those packages to live in a certain directory, and that's the one thing I couldn't get npm to do in a similar way. Also I'm sure using two package managers in a single project will confuse other/new devs in my team...

Sad to see bower is being deprecated. I don't see any disadvantage in keeping it around, tbh...

**Comment by deviousasti** [comment]
@gf3 is there any particular reason for unpublishing from bower?
