### ISSUE TITLE
Webpack boilerplate

### ISSUE THREAD

**Issue by deviousasti** [rotaready/moment-range#158]
The library is around 330 loc, but it looks like there's more than than in webpack boilerplate tacked on in front. Isn't this simple enough to have ambiently? 

Or is this how things are like now? 
Should I just roll with it?

**Comment by B3nCr** [comment]
Not a solution but, the only way I can get this library to work is by using the webpacked version from cloudflare. I can't just `bower install` it and manually use the file in the lib folder even if I compile it down to es5.

Am I missing something in the docs about how to install it?

**Comment by gf3** [comment]
we can look into using something like [rollup](https://rollupjs.org) for the production builds, which may have less boilerplate

**Comment by gf3** [comment]
after doing some testing, i've found that currently:

- `moment-range` source is `10kb`
- when compiled with its deps by webpack it's `29kb`
- when compiled with its deps by rollup it's `20kb`
- when compiled with its deps by webpack in production mode it's `12kb`

i'll submit a PR to use webpack's production mode by default

**Comment by gf3** [comment]
Closed by #205
