### ISSUE TITLE
Multiple date ranges find intersection in ALL ranges

### ISSUE THREAD

**Issue by stursby** [rotaready/moment-range#165]
How would I go about trying to find the overlapping days in multiple ranges?

For example if I had 3 date ranges
RED       `5/3/2017 - 5/9/2017`
GREEN  `5/4/2017 - 5/10/2017`
BLUE     `5/8/2017 - 5/12/2017`

![image](https://cloud.githubusercontent.com/assets/527849/25762920/3ebe7ffe-31a6-11e7-887c-6ca67b9ac020.png)

So I'm trying to get back the date range (or ranges) that ALL THREE overlap.

So the returned range for this example should be `5/8/2017 - 5/9/2017`

**Comment by Rhysjc** [comment]
@stursby I might be misunderstanding, but would you not just loop through the ranges and build up the intersection.

**Comment by ALiangLiang** [comment]
Hi @stursby 
Maybe you can use [moment-ranges#overlaps](https://github.com/ALiangLiang/moment-ranges#overlaps)
