### ISSUE TITLE
How to break from the iterable?

### ISSUE THREAD

**Issue by nealoke** [rotaready/moment-range#166]
I'm wondering how you would break from the iterable provided by `.by('days', momentDay => {...})`. Is this possible and how?

**Comment by Rhysjc** [comment]
Hey @nealoke, if you wrap the result of `.by` in `Array.from`, you can break out of it like you would with any other array.

**Comment by nealoke** [comment]
@Rhysjc thanks :) would you be able to provide a small example? I don't really understand how I would do that.

**Comment by Rhysjc** [comment]
@nealoke If you look at the docs for `.by` there's an example of `Array.from` in there 😁

**Comment by nealoke** [comment]
@Rhysjc ooh waaw, did the documentation change or did I just missed that totally? :D 

Thanks!
