### ISSUE TITLE
What's the benefit of using iterators?

### ISSUE THREAD

**Issue by masylum** [rotaready/moment-range#167]
Since introducing the new API all our IE11 customers can't use our application. I'm not sure the new API solves any pain and it introduces a lot of headaches. Now we have to make our code to support `Symbol` and although I tried it still does not work. I would reconsider going back to the old API.

**Comment by TristanJM** [comment]
Will be discussed here: https://github.com/rotaready/moment-range/issues/172

**Comment by gf3** [comment]
@masylum just added a little explanation to the other issue: https://github.com/rotaready/moment-range/issues/172#issuecomment-352595374
