### ISSUE TITLE
Range.add() should support the 'adjacent' parameter

### ISSUE THREAD

**Issue by cooperised** [rotaready/moment-range#168]
When adding two ranges, it would be great if adjacent ranges could be combined, but although add() calls overlaps() it doesn't have the facility to pass on the 'adjacent' parameter.

**Comment by Rhysjc** [comment]
Hey @cooperised, I think that's a good idea. Would be happy to accept a PR!

**Comment by cooperised** [comment]
PR #187 added

**Comment by TristanJM** [comment]
Will be included in 3.1.0 release
