### ISSUE TITLE
Check if date is in array of ranges

### ISSUE THREAD

**Issue by eskema** [rotaready/moment-range#170]
Hi,

Is there a way to check if a date is in an array of ranges?

I have a bunch of events with multiple dates, some are ranges some are not. Some have multiple ranges and single dates. I'm using Flatpickr and Isotope and I want to filter events if the selected day is contained in an array of ranges that each event has.
Each event has at least one range ( if it's a single day, the range start and end are the same day).
Ideally I would like to get something like this:

```js
// picked with Flatpickr
var myDate = selectedDate;

// each event has a ranges array containing all it's date ranges
var ranges = [range1, range2, range3];

// on Isotope filter function, 
// check if the date is contained in a range contained in ranges
myDate.isContainedIn(ranges);
```

**Comment by Rhysjc** [comment]
Hey @eskema, you could just loop over the array and use `.contains`.

**Comment by ALiangLiang** [comment]
Hi @eskema
Maybe you can use [moment-ranges#contains](https://github.com/ALiangLiang/moment-ranges#contains)
