### ISSUE TITLE
Create range from array of moments (more than 2 moments)

### ISSUE THREAD

**Issue by pie6k** [rotaready/moment-range#171]
What do you think about such interface?

`moment.range([m1, m2, m3, m4, m5]);`

That would create range in such way:
1. From array of moments - take first and last moments
2. use those as start and end of range

So it'd allow passing array of any moments beeing sure you'll have range that covers them all.

**Comment by pronebel** [comment]
what do you mean?

```
var momArr = [m1, m2, m3, m4, m5]
var start = moment.min(momArr);
var end = moment.max(momArr);
moment.range(start,end)

```
is it yours?

**Comment by Rhysjc** [comment]
Hi @pie6k, you could sort the array and then pass the first and last elements in to the constructor. I can understand why you want this added, but I feel like it's better we keep the API simple.
