### ISSUE TITLE
Iteration API returns iterable thats not supported in IE

### ISSUE THREAD

**Issue by millerized** [rotaready/moment-range#172]
>Iteration
>
>Each of the iteration methods return an Iterable, providing a convenient and performant interface to iterating over your ranges by a given period.

Was this API built to be used with transpiled ES6? – IE does not support `for…of` or `Array.from` for iterating on symbol.iterator making this version of the library incompatible with, non-transpiled ES5 codebases.

**Comment by wubzz** [comment]
Agreed, this is a major downer for a library that is supposed to support browsers. Feels like this change was done just because Symbols are a cool new thing, I can't see any other reason really.

From a production perspective there are still tons of customers using IE 11 instead of Edge, not to mention IE 9/10.

I'll be switching back down to version 2.2.0

**Comment by sandstrom** [comment]
FWIW I think iterators could work under Babel + [this polyfill](https://babeljs.io/docs/usage/polyfill)

**Comment by bmuenzenmeyer** [comment]
> FWIW I think iterators could work under Babel + this polyfill

This worked for me

**Comment by gf3** [comment]
we should put a note in the README for devs that need to accommodate IE11

**Comment by gf3** [comment]
firstly, i'm sorry if this caused any issues for those of you that need to support older browsers

there are many benefits to using the iterable/iterator protocols now that [there is broad support for them](http://kangax.github.io/compat-table/es6/#test-well-known_symbols_Symbol.iterator,_existence_a_href=_https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/iterator_title=_MDN_documentation_img_src=_../mdn.png_alt=_MDN_(Mozilla_Development_Network)_logo_width=_15_height=_13_/_/a_nbsp;) across platforms

1. **standardized interface to interact with ranges that work with other tools**
    previously this was not the case since moment-range had to develop its own custom iteration methods. e.g.: now by default users can interact with ranges like arrays (via `Array.from`), use ranges with the spread operator `...`, or loop over them directly using native `for ... of` loops. this is much more natural and powerful
2. **performance improvements**
    one of the nice things about the iterator protocol is that it allows us to lazily produce values in a sequence. this gives us the ability to work with very large ranges more efficiently and improve the performance of our apps
3. **ergonomics**
    using iterables/iterators is a lot more intuitive to those new to JS or even familiar with JS and new to moment range

i hope this helps clear up some of the *why* behind the switch

**Comment by sandstrom** [comment]
@gf3 Good points, I think we should close this issue. There are polyfills + transpilers that can be used for old browsers

**Comment by bmuenzenmeyer** [comment]
> firstly, i'm sorry if this caused any issues for those of you that need to support older browsers

No worries - my posting here and on the material-ui-pickers repo was more an attempt to drop breadcrumbs for futures users, as the polyfilling went one step further than previously reported.

🕵️ 

> we should put a note in the README for devs that need to accommodate IE11

I think that'd be 💯 of you

**Comment by gf3** [comment]
Fixed by #216
