### ISSUE TITLE
Moment's time zones should be preservable 

### ISSUE THREAD

**Issue by aroller** [rotaready/moment-range#175]
See [moment.parseZone()](https://momentjs.com/docs/#/parsing/parse-zone/) for the ability to have a moment that will preserve the time zone in the moment itself.  

Calling `moment.format()` will then print using the original time zone.  

The same should be capable for momentRange.

```
it('should allow moments to keep given time zone', function() {
      const start = '2015-01-17T09:50:04+03:00';
      const end   = '2015-04-17T08:29:55-04:00';
      const timeInterval = start + '/' + end;
      const range = moment.parseZoneRange(timeInterval);
      expect(range.toString()).equal(timeInterval);
});
```

I persist the moment range in the database using the ISO format provided from date range and it is important to keep the relative time zone.

**Comment by TristanJM** [comment]
Thanks for the PR! Included this in 3.1.0
