### ISSUE TITLE
[Suggestion] Add minified version to /dist

### ISSUE THREAD

**Issue by neokio** [rotaready/moment-range#179]
I'm half thinking "Yeah this is undoubtedly necessary", and half cringing at what it says about me (i.e. laziness) that I find this necessary.

I have a project with a dozen js modules, all maintained via NPM, including moment and (to my total delight) moment-range. I use gulp to build/concat these into one file for optimized http requests. Every other module provides a `.min.js` version. It's really no big deal for me to add 6 lines for the convenience of automating the minification of this one file, it's just ... inelegant?

![screen shot 2017-07-12 at 10 44 11 am](https://user-images.githubusercontent.com/146623/28123496-16e01a96-66ef-11e7-8ac8-efc699e86c31.png)

There are certainly better reasons than mine for you to offer a minified version. I just thought I'd voice in and suggest the idea, as others might find it equally useful :)

Cheers!

**Comment by JochenDiekenbrock** [comment]
You might consider using webpack instead of handcrafted gulp tasks. Webpack will handle the minification of your dependencies while bundling.
Having done the same step just recently, it may take a few hours, but I feel it's worth the effort.

**Comment by neokio** [comment]
You're right of course, I'm using a task runner as a bundler. 
Webpack has been on my must-learn-list for almost 2 years now.
Thanks for the nudge :)

**Comment by gf3** [comment]
Closed by #205
