### ISSUE TITLE
Deprecation warning

### ISSUE THREAD

**Issue by alesmenzelsocialbakers** [rotaready/moment-range#180]
Range by range gives deprecation warning messages:

```
// Repro:
const range = moment.range([
	moment.tz('Asia/Jakarta').subtract(3, 'days').startOf('day'),
	moment.tz('Asia/Jakarta')
]);
const byRange = moment.range([
	moment('2017-01-01 00:00:00'),
	moment('2017-01-01 00:15:00')
]);

const quaters = Array.from(range.by(byRange));
```

`Deprecation warning: moment().add(period, number) is deprecated. Please use moment().add(number, period). See http://momentjs.com/guides/#/warnings/add-inverted-param/ for more info.`

**Comment by Rhysjc** [comment]
Hey @alesmenzelsocialbakers, we only use `moment().add` in one place in the lib, and we pass the parameters in the correct order. You might need to check which version you're using, or it's possible this warning could be triggered elsewhere in your code base?
