### ISSUE TITLE
DateRange.Add adjacent ranges to be added

### ISSUE THREAD

**Issue by michaltalaga** [rotaready/moment-range#185]
it is now possible to check for overlap:
range.overlaps(otherRange, { adjacent: true })

but this will return null

range.add(otherRange);

**Comment by TristanJM** [comment]
Hey @michaltalaga,
Would you be able to provide a more detailed code example including the values of your range variables?

**Comment by michaltalaga** [comment]
var r1 = moment.range('2017-01-01', '2017-01-05');
var r2 = moment.range('2017-01-05', '2017-01-10');
r1.overlaps(r2); // false
r1.overlaps(r2, { adjacent: true }); // true
r1.add(r2); // null <----- should return joint range

**Comment by TristanJM** [comment]
This is definitely in scope for a future release - as noted in [this issue](https://github.com/rotaready/moment-range/issues/168), we are happy to accept a PR!
