### ISSUE TITLE
Saved 939 new dependencies...

### ISSUE THREAD

**Issue by alexgvozden** [rotaready/moment-range#189]
not sure, but can you explain me how it's possible to install 939 new dependencies by installing moment-range...

**Comment by gf3** [comment]
moment-range has [only one dependency](https://github.com/rotaready/moment-range/blob/master/package.json#L83), however there are many development dependencies that are only required if you're working on feature development

**Comment by Rhysjc** [comment]
Hey @alexgvozden, as @gf3 said above, we've only got one dependency. If you clone this repo and run an `npm install`, you'll be installing all our development dependencies, and their dependencies, and so on. If you're not planning on adding feature to moment-range, I recommend you install from npm. I'll close this issue now.

**Comment by alexgvozden** [comment]
no I just installed your package, nevermind...
