### ISSUE TITLE
Unexpected Token Import

### ISSUE THREAD

**Issue by txa1562** [rotaready/moment-range#190]
I am getting this error when I try to do a browser install:
`Uncaught SyntaxError: Unexpected token import`

This happens on line 1 of moment-range.js

**Comment by TristanJM** [comment]
Hey,

This probably means you haven't correctly linked in moment.js before moment-range.

Try adding the first script tag as 
`<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.18.1/moment.js"></script>`

And then the second script tag should reference to your downloaded version of moment-range.js.
Please see the docs for the code example :)
