### ISSUE TITLE
Wrong locales when using in different files

### ISSUE THREAD

**Issue by bloodcarter** [rotaready/moment-range#191]
Also see https://github.com/moment/moment/issues/4171#issuecomment-329429471
I cannot explain this weird behaviour. Consider following files:
```
//file1.js
var Moment = require('moment');
Moment.locale('ru-RU');
const MomentRange = require('moment-range');
const moment = MomentRange.extendMoment(Moment);

//file2.js
var Moment = require('moment-timezone');
Moment.locale('en-US');
const MomentRange = require('moment-range');
const moment = MomentRange.extendMoment(Moment);

//somewhere later in the same file
let m = moment();
m.locale(); // 'ru'  - unexpected behaviour!!!!!!

```
If all moment instances are local, the subsequent locale calls shouldn't change locales of the existing library instances, right? And if not, then how do I maintain several different locales across multiple files?

Momentjs version is 2.18.1

**Comment by jontelm** [comment]
I think I have seen this before. You maybe have another lib that require moment and sets the setDefault
https://github.com/moment/moment/issues/3754

in your
//somewhere later in the same file
let m = moment();
change that line to
import m from '...//your/path/file2.js
