### ISSUE TITLE
On es5 in typescript, which version of moment-range and @types/moment-range should I use?

### ISSUE THREAD

**Issue by shrutic** [rotaready/moment-range#197]
I currently get below error when I try to use the latest moment-range and the @types/moment-range npm packages

node_modules/@types/moment-range/index.d.ts(28,93): error TS2304: Cannot find name 'Iterable'.
node_modules/@types/moment-range/index.d.ts(30,85): error TS2304: Cannot find name 'Iterable'.
node_modules/@types/moment-range/index.d.ts(52,100): error TS2304: Cannot find name 'Iterable'.
node_modules/@types/moment-range/index.d.ts(54,92): error TS2304: Cannot find name 'Iterable'.
npm ERR! code ELIFECYCLE

It is not an option to change to ES6 right now

**Comment by gf3** [comment]
two things:

1) proper typescript definitions [are coming](https://github.com/rotaready/moment-range/pull/204)
2) ensure you have `"lib": ["es2015", "es2015.iterable"]` under `"compilerOptions"` in your `tsconfig.json`

**Comment by gf3** [comment]
Closed by #204
