### ISSUE TITLE
sh: yarn command not found

### ISSUE THREAD

**Issue by killmenot** [rotaready/moment-range#203]
Hi guys,

Got the following error when tried to install moment-range when no yarn installed:
<img width="546" alt="screenshot 2017-12-14 13 22 57" src="https://user-images.githubusercontent.com/119337/33987711-ebad9d40-e0d2-11e7-8ec2-23a46d1a2e3a.png">

Maybe use `npm` in package.json?

**Comment by gf3** [comment]
hi @killmenot, what command did you run to get that output?

**Comment by killmenot** [comment]
@gf3 just `npm install` (`yarn` is not installed)

**Comment by gf3** [comment]
@killmenot i've got a PR up to fix the issue—should be taken care of soon! thank you

**Comment by killmenot** [comment]
@gf3 thx!

**Comment by gf3** [comment]
Closed by #205
