### ISSUE TITLE
range.by("weeks",callback()) not giving all the ranges

### ISSUE THREAD

**Issue by vigneshrajarr** [rotaready/moment-range#218]
range.by("weeks",callback()) gives the weekly ranges correctly for some and missing the last range in some.
Example: Giving all ranges.
![screen shot 2018-02-09 at 6 26 29 pm](https://user-images.githubusercontent.com/11133062/36028873-bf772d2e-0dc6-11e8-86af-c9251920815e.png)

Example: Missing last range.
![screen shot 2018-02-09 at 5 48 19 pm](https://user-images.githubusercontent.com/11133062/36028778-552f0ba8-0dc6-11e8-9713-86c313a37b9f.png)

moment-range Version : 2.1.0

**Comment by gf3** [comment]
hi @vigneshrajarr, this is because the range is from `06/01`-`30/01` and the period after the last week in your range is from `28/01`-`30/01` which is not a full week 

to accomodate for this you could do something like:

``` js
const start = moment('2018-01-06').startOf('week');
const end = moment('2018-01-30').endOf('week');
const range = moment.range(start, end);

range.by('weeks', function(moment) {
  // ...
});
```

**Comment by vigneshrajarr** [comment]
Thanks @gf3 . It worked for my requirement.

**Comment by TristanJM** [comment]
Following `4.0.0` release, this can also be achieved with `range.snapTo()` (https://github.com/rotaready/moment-range/pull/220):

``` js
const range = moment.range(start, end).snapTo('week');
// automatically snaps the range to the start and end of the week for you
```
