### ISSUE TITLE
Installing moment-range via Bower in Visual Studio 2017

### ISSUE THREAD

**Issue by rprimora** [rotaready/moment-range#219]
After I pull the package from bower I can see it in my project. I proceed by adding the moment-range.js that is located in wwwroot/lin/moment-range/lib to my page.

This is the error I get:

> Uncaught SysntaxError: Unexpected identifier.

Sure enough the browser cannot parse this since it starts with this
```
import moment from 'moment';
import Symbol from 'es6-symbol';
```

This happens with moment.js aswell but they provide compiled lib so I can include that and have no problems. Am i missing something here?

**Comment by gf3** [comment]
hi @rprimora—bower support is discontinued please use the npm package or the jsdelivr CDN

**Comment by rprimora** [comment]
Okay, thank you for the info.
