### ISSUE TITLE
How can I use this plugin with moment package together?

### ISSUE THREAD

**Issue by newdevsoft7** [rotaready/moment-range#221]
Hi. I am building a website with Angular 5, and I use moment package already. And I want to use this plugin with moment package. How can I do this?

`import * as moment from 'moment';`
 `import * as moment from 'moment-precise-range-plugin';`

But I have got errors because of duplication, do you have any idea to use both moment and moment packages together as the same namespace?

**Comment by Lesbraslongs** [comment]
hey @newdevsoft7 did you get an answer ?

**Comment by newdevsoft7** [comment]
I can't find the solution.

**Comment by gf3** [comment]
@newdevsoft7 @Lesbraslongs this is **not** the repo for `'moment-precise-range-plugin'`
