### ISSUE TITLE
It would be better to return empty array than null - intersect

### ISSUE THREAD

**Issue by Konradox** [rotaready/moment-range#231]
It would allow use construction like:
range1.intersect(range2).toDate().length;

**Comment by TristanJM** [comment]
An empty array wouldn't make much sense to the library:

`instersect` returns the range object of the crossover time. If there is no crossover time, then there can't be a range object (we can't return a range object with no moments). So returning `null` is intuitive.

Typical use case would be like this:
```javascript
let intersect = range1.intersect(range2);
if (intersect)  // use the intersecting range
else // handle unexpected
```

In your example
`range1.intersect(range2).toDate().length;` 
would only ever return `2` on a valid range anyway as it equates to `[startmoment, endmoment]`

**Comment by Konradox** [comment]
I'm sorry, my bad. I had a really wierd case.

**Comment by TristanJM** [comment]
Thanks for the suggestion :)
