### ISSUE TITLE
range.by('day') returns bad collection

### ISSUE THREAD

**Issue by micodel** [rotaready/moment-range#235]
Array.from(range.by('day')) returns an array with the correct number of elements, but every element is the first day / date object.

The same is true for range.by('days')

**Comment by gf3** [comment]
hey @micodel did you mean to close this issue?

**Comment by micodel** [comment]
Yes I did. Thanks for the follow up.

The issue appears to be with how moment stores the input (_i value) when built from a range. Every element had the first range date as the input, the but date (_d value) turned out to be correct and functional.

I ran into the same issue with other libraries and a manual iterator as well.

**Comment by Marina-R** [comment]
Hi all! 
@micodel , what is the solution for this issue? I'm facing the same bug. Thanks.

**Comment by wmlutz** [comment]
I'm also running into this.
