### ISSUE TITLE
unable to format the range

### ISSUE THREAD

**Issue by slim-hmidi** [rotaready/moment-range#245]
I wrote this code's snippet:
```
const start = moment('2018-04-01').format('YYYY-MM-DD');
const end   = moment('2018-04-30').format('YYYY-MM-DD');
const range1 = moment.range(start, end);
```
I got this result:
```
range1:  [ 2018-03-31T23:00:00.000Z, 2018-04-29T23:00:00.000Z ]
```
I didn't found an option to make it like this:
```
range1:  [ 2018-03-31, 2018-04-29 ]
```
First of all I didn't know why the there's subtraction of a the start_date and end_date, then is there any solution to format the date to be like the example above?

**Comment by TristanJM** [comment]
The range is built between 2 moment objects, what are you using to print out that first result?
This part of the docs might help you: https://github.com/rotaready/moment-range#conversion

If you want to get the range start you simply call `range1.start`
```js
range1.toString(); // 2018-04-01T00:00:00/2018-04-30T00:00:00

range1.start.format('YY-MM-DD'); // 18-04-01
range1.end.format('YY-MM-DD'); // 18-04-30
```
