### ISSUE TITLE
The type declarations don't seem to be up to date with the actual implementation.

### ISSUE THREAD

**Issue by eweitnauer** [rotaready/moment-range#249]
For example, the method `add` is implemented as

```
 add(other, options = { adjacent: false }) {
   ...
}
```

but the type declaration is `add(other: DateRange): ?DateRange;` for flow and `add(other: DateRange): DateRange | undefined;` for typescript – both missing the `options` parameter.

Maybe just use the declarations from [@types/moment-range](https://www.npmjs.com/package/@types/moment-range)?

**Comment by webleaf** [comment]
Also typings don't allow calling `moment.range()` w/o arguments

**Comment by TristanJM** [comment]
This is fixed in`4.0.2` and will be published on Monday :)
