### ISSUE TITLE
Close open-ended range

### ISSUE THREAD

**Issue by strarsis** [rotaready/moment-range#266]
An open-ended range has been created, how can it later be closed by using another moment() time? 
It doesn't seem to work by assigning it to `.end`.

**Comment by TristanJM** [comment]
This should work:
```js
const r = moment.range(moment('2017-01-01T13:30:00'));
console.log(r.toString());  // 2017-01-01T13:30:00+00:00/275760-09-13T01:00:00+01:00
r.end = moment();
console.log(r.toString());  // 2017-01-01T13:30:00+00:00/2019-10-07T10:58:58+01:00
```

Otherwise, feel free to use `.copy()` and pass in the old range's `start` and your new `end`.
