### ISSUE TITLE
Question about start date later than end date

### ISSUE THREAD

**Issue by zh3ngyuan** [rotaready/moment-range#268]
**version: v4.0.2**
when I run the following script:
~~~javascript
var start = moment('10/11/2019', 'MM/DD/YYYY');
var end = moment('10/05/2019', 'MM/DD/YYYY');
Array.from(moment.range(start, end).by('day')).map(function(date) {
    return date.format()
});
~~~
I got the output like this
~~~javascript
// [
//     "2019-10-11T00:00:00-07:00", 
//     "2019-10-12T00:00:00-07:00",
//     "2019-10-13T00:00:00-07:00", 
//     "2019-10-14T00:00:00-07:00", 
//     "2019-10-15T00:00:00-07:00", 
//     "2019-10-16T00:00:00-07:00", 
//     "2019-10-17T00:00:00-07:00"
// ]
~~~
Apparently, the result is incorret, and what I expected should be `[]` or `[endDate, ... , startDate]`

I was wondering if there is any validation for the case that start date is later than the end date? otherwise, I need to validate it by myself before generate the range.

**Comment by TristanJM** [comment]
Hey, we've left validating the order of the input dates to the user. You're correct in that you should validate this first and ensure the end moment comes after the start of the range :)

FYI We've raised https://github.com/rotaready/moment-range/pull/201 and are considering automatically sorting the order of inputs

**Comment by TristanJM** [comment]
Please feel free to reopen the issue if you spot some weird behaviour! 😃
