### ISSUE TITLE
Sort an array of Ranges

### ISSUE THREAD

**Issue by athenawisdoms** [rotaready/moment-range#280]
Hello! 

Given an array of dates ranges, how can we sort them in ascending order of the start date? 

If 2 start dates are identical, it might make sense to then sort these ranges in ascending order of the end date. If the library does not contain function(s) to achieve this, I am fine with using lodash if needed.

Thanks!

**Comment by carlholloway** [comment]
Hello hello,

I haven't tested it but this should be what you're after:

```javascript
const array = [moment.range(w, x), moment.range(y, z), ...];

array.sort((a, b) => {
  const diff = b.start.valueOf() - a.start.valueOf();
  return diff === 0 ? b.end.valueOf() - a.end.valueOf() : diff;
});
```

Hope this helps!
