### ISSUE TITLE
Should moment-range not use UTC mode?

### ISSUE THREAD

**Issue by wmertens** [rotaready/moment-range#74]
Since moment-range is focused on dates, perhaps all dates should be expressed in as UTC dates, no matter what the local timezone.

**Comment by gf3** [comment]
@wmertens i think in this case it would be up to the end user. in theory it'd be nice, but under the hood we're still using groß Date objects. it's sort of a leaky abstraction but i'm not sure what we could do about it?

**Comment by polizinha** [comment]
+1

**Comment by gf3** [comment]
i don't like the idea of forcing a timezone on people, there could be cases where people want to be timezone aware
